#默认开发环境
spring:
  profiles.active: dev
---
#开发环境
spring:
  profiles: dev
  datasource.url: jdbc:mysql://localhost:3306/securityTest?characterEncoding=utf-8&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  datasource.username: root
  datasource.password: root
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
